### ISSUE TITLE
OCI::ObjectStorage::ObjectStorageClient#get_object blows up on badly compressed file

### ISSUE THREAD

**Issue by nirvdrum** [oracle/oci-ruby-sdk#12] opened 2018-08-30 18:36 UTC
This is probably related to the auto-inflate behavior I've reported in #11.

In this case, if I have an object in OCI object storage and had set the `Content-Encoding` header to `deflate`, but the contents of the file are not deflated properly, the client blows up with the following error:

```
OCI::Errors::NetworkError: /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/net/http/response.rb:333:in `stream_check': undefined method `closed?' for nil:NilClass (NoMethodError)
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/net/http/response.rb:202:in `read_body'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/net/http/response.rb:229:in `body'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/oci-2.3.5/lib/oci/errors.rb:112:in `to_s'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb.rb:502:in `write'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb.rb:502:in `print'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb.rb:502:in `block (2 levels) in eval_input'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb.rb:627:in `signal_status'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb.rb:490:in `block in eval_input'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `loop'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `catch'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb.rb:489:in `eval_input'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb.rb:430:in `block in run'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb.rb:429:in `catch'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb.rb:429:in `run'
        from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/2.4.0/irb.rb:385:in `start'
        from /home/kjmenard/.rbenv/versions/2.4.4/bin/irb:11:in `<main>'
```

In contrast, the CLI tool (`oci-cli`) available for Python will get the file in its original form just fine. Certainly, I shouldn't be storing objects where the encoding and the contents don't align -- for this I was just testing something. But I don't think this needs to raise a `NoMethodError` on `nil` either.

**Comment by andy-miles** [comment] 2018-09-05 19:30
I'll look into writing some tests to repro this issue as net::http tries to perform some magic under the hood.

**Comment by andy-miles** [comment] 2018-09-19 00:28
I'm unable to reproduce this issue as deflate is already defined in the `accept-enconding` header by default.  Upon inspection of the net::http source code, it would appear that the `@socket` reference was set to `nil`:
```
def stream_check
    # ruby/2.4.0/net/http/response.rb:333
    raise IOError, 'attempt to read body out of block' if @socket.closed?
end
```

From a cursory search online, I've found that this may be indicative of a socket being closed in the middle of the stream.  

Some follow-up questions:

1. Are you seeing this issue consistently?
2. Are you trying to download from Object Storage service using a proxy?

**Comment by andy-miles** [comment] 2018-09-27 21:43
Any updates to the questions I asked?

**Comment by nirvdrum** [comment] 2018-10-04 17:53
Sorry. I missed the notification. This is 100% reproducible. I think there's a disconnect between the issue I described and what you're looking for. Hopefully this code snippet helps:

```
conn.put_object(OCI_TENANCY, OCI_BUCKET_NAME, 'file.txt', "plain text", content_encoding: 'deflate')

conn.get_object(OCI_TENANCY, OCI_BUCKET_NAME, 'file.txt')
```

So, the `Content-Encoding` header is wrong. But, the contents should still be retrievable. Because the client always sets `Accept-Encoding`, which I posit is incorrect, it attempts to inflate the file and naturally fails in doing so. I think if #11 is addressed, this issue goes away. But if the default value for `Accept-Encoding` is here to stay, this issue may need to be addressed.

**Comment by nirvdrum** [comment] 2018-10-04 18:03
As for the second question, I am not using a proxy.

**Comment by andy-miles** [comment] 2018-10-04 20:38
Since the object was stored using a non-default content-encoding, you'll need to pass an explicit `accept_encoding` in the `get_object()` call.

Below is a sample app that demonstrates how to retrieve an object with a non-default content-encoding and also demonstrates the reproduction case:
```
require 'oci'
require 'pp'

bucket_name = 'Test'
object_storage_client = OCI::ObjectStorage::ObjectStorageClient.new

namespace = 'TestNamespace'

object_name = 'TestObject'
put_object_response = object_storage_client.put_object(
  namespace,
  bucket_name,
  object_name,
  'Test object content',
  content_type: 'text/plain',
  content_encoding: 'deflate'
)
puts 'Put object in bucket with deflate encoding'
puts '=' * 20
pp put_object_response.headers

# Retrieve works with explicit accept_encoding and content_type as of
# Ruby SDK release 2.3.7 or greater
begin
  puts
  puts "Getting object with explicit accept_encoding..."
  test_object = object_storage_client.get_object(
    namespace,
    bucket_name,
    object_name,
    accept_encoding: 'deflate',
    content_type: 'text/plain')
  pp test_object.data
rescue OCI::Errors::ServiceError, OCI::Errors::NetworkError => e
  puts 'Attempt to get archived object'
  puts '=' * 20
  puts e.to_s
end

# Retrieve without explicit accept_encoding results in NET::HTTP throwing an exception
# due to a non-default content-encoding value of 'deflate'
begin
  puts
  puts "Getting object without explicit accept_encoding (should throw an error)..."
  test_object = object_storage_client.get_object(namespace, bucket_name, object_name)
  pp test_object.data
rescue OCI::Errors::ServiceError, OCI::Errors::NetworkError => e
  puts 'Attempt to get archived object'
  puts '=' * 20
  puts e.to_s
end

```

**Comment by andy-miles** [comment] 2018-10-04 21:03
Please reopen this issue if the recommendation above doesn't work for you.

**Closed by andy-miles** 2018-10-04 21:03 UTC
